title: Sydney Vach
author: Sydney Vach (she/her)
email: sydney_vach@college.harvard.edu
description: > # this means to ignore newlines until "baseurl:"
  Harvard student studying Astrophysics (& Physics?). My research interestes are the detection
  and classification of exoplanets, as well as planetary formation and dynamics. I am looking
  to apply for Ph.D programs starting Fall 2022. 

# social links
twitter_username: Astro_Sydney # DO NOT include the @ character, or else the build will fail!
github_username:  sydney-vach # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
